version: '2'

services:
  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    restart: always
    command: -R -A /%DOMAIN_NAME%/%MACHINE_IP% -S/#/%NAMESERVER_IP%
    networks:
      back:
        ipv4_address: %DNSMASQ_IP%
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN

networks:
  back:
    ipam:
      driver: default
      config:
        - subnet: %BACK_SUBNET%
          gateway: %BACK_GATEWAY%
