version: '2'
services:
  consul:
    restart: always
    image: consul:1.0.0
    command: "agent -ui -server -client 0.0.0.0 -advertise 127.0.0.1 -bootstrap-expect 1"
    labels:
      - "traefik.backend=consul"
      - "traefik.port=8500"
      - "traefik.frontend.rule=Host:%CONSUL_HOST%"
    networks:
      - web

networks:
  web:
    external:
      name: traefik_webgateway
