---
resources:
- name: click-count-repo
  type: git
  source:
    uri: https://github.com/clook/click-count.git
    branch: docker-deploy

- name: click-count-image
  type: docker-image
  source:
    repository: registry.xebia-test:80/click-count
    insecure_registries: ["registry.xebia-test:80"]


jobs:
- name: build-image
  public: true
  plan:
  - get: click-count-repo
    trigger: true
  - task: build-war
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: "maven"
          tag: 3
      inputs:
        - name: click-count-repo
      outputs:
        - name: click-count-war
      run:
        dir: click-count-repo
        path: sh
        args:
          - -c
          - "mvn clean package && mv target Dockerfile ../click-count-war/"
  - put: click-count-image
    params:
      build: click-count-war
      tag: click-count-repo/.git/ref

- name: deploy-staging
  plan:
  - get: click-count-repo
    passed:
      - build-image
    trigger: true
  - task: deploy-staging
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: "williamyeh/ansible"
          tag: debian9
      inputs:
        - name: click-count-repo
      run:
        dir: click-count-repo/ci_infra/fly/pipelines/deploy
        path: sh
        args:
          - -c
          - "./docker_deploy.sh"
          - click-count-repo/.git
      params:
        SSH_KEY: {{docker-ssh-key}}
        DEPLOY_ENV: staging

- name: deploy-prod
  plan:
  - get: click-count-repo
    passed:
      - deploy-staging
    trigger: false
  - task: deploy-prod
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: "williamyeh/ansible"
          tag: debian9
      inputs:
        - name: click-count-repo
      run:
        dir: click-count-repo/ci_infra/fly/pipelines/deploy
        path: sh
        args:
          - -c
          - "./docker_deploy.sh"
          - click-count-repo/.git
      params:
        SSH_KEY: {{docker-ssh-key}}
        DEPLOY_ENV: production
