---
resources:
- name: click-count-repo
  type: git
  source:
    uri: https://github.com/xebia-france/click-count.git

jobs:
- name: build-war
  public: true
  plan:
  - get: click-count-repo
  - task: build-war
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: "maven"
          tag: 3
      inputs:
        - name: click-count-repo
      run:
        dir: click-count-repo
        path: mvn
        args: ["clean", "package"]
