---
resources:
- name: click-count-repo
  type: git
  source:
    uri: https://github.com/clook/click-count.git

- name: click-count-image
  type: docker-image
  source:
    repository: registry.xebia-test/click-count
    insecure_registries: ["registry.xebia-test/click-count"]

jobs:
- name: build-war
  public: true
  plan:
  - get: click-count-repo
  - task: build-war
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: "maven"
          tag: 3
      inputs:
        - name: click-count-repo
      outputs:
        - name: click-count-war
      run:
        dir: click-count-repo
        path: sh
        args:
          - -c
          - "mvn clean package && mv target Dockerfile ../click-count-war/"
  - put: click-count-image
    params:
      build: click-count-war
