version: '2'

services:
  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    command: -A /xebia-test/192.168.33.10
    networks:
      back:
        ipv4_address: 192.168.34.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN

networks:
  back:
    ipam:
      driver: default
      config:
        - subnet: 192.168.34.0/28
          gateway: 192.168.34.1
