---
- name: Deploy application using docker
  hosts: xebia-test
  remote_user: root
  become: true
  tasks:
    - name: pull docker image
      docker_image:
        state: present
        name: "registry.xebia-test:80/click-count:{{ docker_tag }}"
        tag: "{{ docker_tag }}"

    - name: run via docker
      docker_container:
        name: "click-count-{{ env }}"
        image: "registry.xebia-test:80/click-count:{{ docker_tag }}"
        labels:
          traefik.backend: "click-count-{{ env }}"
          traefik.port: "8080"
          traefik.docker.network: "traefik_webgateway"
          traefik.frontend.rule: "Host:{{ host_name }}.xebia-test"
        state: started
        restart_policy: always
        env:
          REDIS_HOST: "{{redis_host}}"
        etc_hosts:
          redis: "{{redis_host}}"
        networks:
          - name: "traefik_webgateway"
